apiVersion: apps/v1
kind: Deployment
metadata:
  name: sensor-sim-space
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sensor-sim-space
  template:
    metadata:
      labels:
        app: sensor-sim-space
    spec:
      containers:
        - name: sensor-sim
          image: ghcr.io/ryanwelchtech/sentinel-sda-sensor-sim:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: SENSOR_TYPE
              value: "space"
            - name: INGEST_URL
              value: "http://ingestion-gateway:8000/observations"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: sentinel-jwt
                  key: JWT_SECRET
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: sentinel-config
                  key: LOG_LEVEL
          ports:
            - containerPort: 8000
