apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sentinel-sda

resources:
  - namespace.yaml
  - services/redis-svc.yaml
  - services/ingestion-gateway-svc.yaml
  - services/track-api-svc.yaml

  - deployments/redis-deploy.yaml
  - deployments/ingestion-gateway-deploy.yaml
  - deployments/validation-service-deploy.yaml
  - deployments/fusion-engine-deploy.yaml
  - deployments/track-api-deploy.yaml
  - deployments/mission-optimizer-deploy.yaml
  - deployments/tasking-service-deploy.yaml
  - deployments/sensor-sim-radar-deploy.yaml
  - deployments/sensor-sim-optical-deploy.yaml
  - deployments/sensor-sim-space-deploy.yaml

  - configmaps/app-config.yaml

  - networkpolicies/default-deny.yaml
  - networkpolicies/allow-same-namespace.yaml
