apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: ghcr.io/ryanwelchtech/sentinel-sda-ingestion-gateway
    newName: sentinel-sda-ingestion-gateway
    newTag: local

  - name: ghcr.io/ryanwelchtech/sentinel-sda-validation-service
    newName: sentinel-sda-validation-service
    newTag: local

  - name: ghcr.io/ryanwelchtech/sentinel-sda-fusion-engine
    newName: sentinel-sda-fusion-engine
    newTag: local

  - name: ghcr.io/ryanwelchtech/sentinel-sda-track-api
    newName: sentinel-sda-track-api
    newTag: local

  - name: ghcr.io/ryanwelchtech/sentinel-sda-mission-optimizer
    newName: sentinel-sda-mission-optimizer
    newTag: local

  - name: ghcr.io/ryanwelchtech/sentinel-sda-tasking-service
    newName: sentinel-sda-tasking-service
    newTag: local

  - name: ghcr.io/ryanwelchtech/sentinel-sda-sensor-sim
    newName: sentinel-sda-sensor-sim
    newTag: local

  - name: ghcr.io/ryanwelchtech/sentinel-sda-mission-planning-agent
    newName: sentinel-sda-mission-planning-agent
    newTag: local

