apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingestion-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingestion-gateway
  template:
    metadata:
      labels:
        app: ingestion-gateway
    spec:
      containers:
        - name: ingestion-gateway
          image: ghcr.io/ryanwelchtech/sentinel-sda-ingestion-gateway:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: sentinel-jwt
                  key: JWT_SECRET
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: sentinel-config
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: sentinel-config
                  key: REDIS_PORT
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: sentinel-config
                  key: LOG_LEVEL
          ports:
            - containerPort: 8000
